-- 이벤트브릿지 시연 데이터
-- courses 테이블에 공고 14건(이벤트 6개)을 넣습니다.
-- description은 vue-frontend/src/api/posting.js의 섹션 규약을 따릅니다.
-- 실행: docker exec -i lecturedb mariadb -umanager -pSqlDba-1 lecture_db < demo-data.sql

SET NAMES utf8mb4;
DELETE FROM enrollments;
DELETE FROM payments;
DELETE FROM courses;
ALTER TABLE courses AUTO_INCREMENT = 1;
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('주무대 및 음향 설비 설치', '[이벤트] 서울 한강 여름축제\n[기간] 2026-08-20 ~ 2026-08-30\n[마감] 2026-08-14\n[지역] 서울 영등포\n[기관] 서울특별시청\n[과업] 물빛무대 12m×8m 가설 및 음향 시스템(라인어레이 8기) 설치·운영, 행사 종료 후 철거까지 포함합니다.\n[자격요건]\n업종: 무대·음향 설치업\n업력: 5년 이상\n유사 실적: 8건 이상', 'FRONTEND', 68000000, 2, 4, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사 부스 60동 설치·철거', '[이벤트] 서울 한강 여름축제\n[기간] 2026-08-20 ~ 2026-08-30\n[마감] 2026-08-17\n[지역] 서울 영등포\n[기관] 서울특별시청\n[과업] 홍보관·체험관 부스 60동(3m×3m) 설치, 전기 인입 및 야간 조명 포함. 우천 대비 차수 시공 필요.\n[자격요건]\n업종: 전시·부스 설치업\n업력: 3년 이상\n유사 실적: 5건 이상', 'BACKEND', 42000000, 2, 3, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사장 안전관리 인력 운영', '[이벤트] 서울 한강 여름축제\n[기간] 2026-08-20 ~ 2026-08-30\n[마감] 2026-08-21\n[지역] 서울 영등포\n[기관] 서울특별시청\n[과업] 일 40명 규모 안전요원 배치, 인파 밀집 구간 동선 관리 및 야간 순찰 운영.\n[자격요건]\n업종: 경비·안전관리업\n업력: 3년 이상', 'DEVOPS', 29000000, 2, 6, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('과학 체험존 부스 설치', '[이벤트] 대전 사이언스 페스티벌\n[기간] 2026-09-25 ~ 2026-09-29\n[마감] 2026-08-25\n[지역] 대전 유성\n[기관] 대전광역시청\n[과업] 체험존 부스 45동 설치 및 실험 안전설비(집진·환기) 시공, 전시물 반입 지원 포함.\n[자격요건]\n업종: 전시·부스 설치업\n업력: 3년 이상\n유사 실적: 4건 이상', 'BACKEND', 37500000, 2, 2, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사 홍보물 디자인·제작', '[이벤트] 대전 사이언스 페스티벌\n[기간] 2026-09-25 ~ 2026-09-29\n[마감] 2026-08-28\n[지역] 대전 유성\n[기관] 대전광역시청\n[과업] 포스터·리플릿·현수막·SNS 카드뉴스 디자인 및 인쇄 제작, 옥외광고 게첨 대행 포함.\n[자격요건]\n업종: 광고·디자인업\n업력: 2년 이상', 'MOBILE', 18000000, 2, 5, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('불꽃 연출 중계 영상 제작', '[이벤트] 부산 불꽃축제\n[기간] 2026-10-24 ~ 2026-10-25\n[마감] 2026-08-31\n[지역] 부산 수영\n[기관] 부산광역시청\n[과업] 4K 다원 중계 8기 운용, 실시간 송출 및 하이라이트 편집본 납품.\n[자격요건]\n업종: 영상제작·중계업\n업력: 5년 이상\n유사 실적: 6건 이상', 'SECURITY', 59000000, 2, 1, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('유등 전시 부스 설치', '[이벤트] 진주 남강유등축제\n[기간] 2026-10-01 ~ 2026-10-14\n[마감] 2026-09-10\n[지역] 경남 진주\n[기관] 경남 진주시청\n[과업] 남강변 유등 전시 부스 80동 설치 및 수상 구조물 앵커 시공, 야간 조명 연동 포함.\n[자격요건]\n업종: 전시·부스 설치업\n업력: 3년 이상\n유사 실적: 5건 이상', 'BACKEND', 48000000, 2, 7, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('개막식 무대·음향 운영', '[이벤트] 진주 남강유등축제\n[기간] 2026-10-01 ~ 2026-10-14\n[마감] 2026-09-12\n[지역] 경남 진주\n[기관] 경남 진주시청\n[과업] 개·폐막식 주무대 설치와 음향·조명 오퍼레이팅, 리허설 2회 지원 포함.\n[자격요건]\n업종: 무대·음향 설치업\n업력: 5년 이상\n유사 실적: 6건 이상', 'FRONTEND', 54000000, 2, 3, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사 운영 인력 배치', '[이벤트] 진주 남강유등축제\n[기간] 2026-10-01 ~ 2026-10-14\n[마감] 2026-09-15\n[지역] 경남 진주\n[기관] 경남 진주시청\n[과업] 안내·티켓·주차 운영 인력 일 60명 배치 및 교육, 다국어 안내요원 6명 포함.\n[자격요건]\n업종: 행사운영 대행업\n업력: 2년 이상', 'DATA_SCIENCE', 26000000, 2, 4, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('커피 시음존 부스 설치', '[이벤트] 강릉 커피축제\n[기간] 2026-10-08 ~ 2026-10-11\n[마감] 2026-09-18\n[지역] 강원 강릉\n[기관] 강릉시청\n[과업] 시음존 부스 40동 설치, 급배수 및 전기 인입 시공, 위생 설비 포함.\n[자격요건]\n업종: 전시·부스 설치업\n업력: 3년 이상', 'BACKEND', 31000000, 2, 2, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사 케이터링 운영', '[이벤트] 강릉 커피축제\n[기간] 2026-10-08 ~ 2026-10-11\n[마감] 2026-09-20\n[지역] 강원 강릉\n[기관] 강릉시청\n[과업] 내빈·스태프 대상 일 300식 케이터링 운영 및 위생관리, 폐기물 처리 포함.\n[자격요건]\n업종: 단체급식·케이터링업\n업력: 2년 이상', 'DATABASE', 22000000, 2, 3, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('비빔밥 체험존 무대 설치', '[이벤트] 전주 비빔밥축제\n[기간] 2026-10-15 ~ 2026-10-18\n[마감] 2026-09-22\n[지역] 전북 전주\n[기관] 전주시청\n[과업] 체험존 야외무대 설치 및 음향 운영, 요리 시연용 조리대 8기 설치 포함.\n[자격요건]\n업종: 무대·음향 설치업\n업력: 3년 이상', 'FRONTEND', 39000000, 2, 1, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('행사장 안전인력 및 의무실 운영', '[이벤트] 전주 비빔밥축제\n[기간] 2026-10-15 ~ 2026-10-18\n[마감] 2026-09-25\n[지역] 전북 전주\n[기관] 전주시청\n[과업] 안전요원 일 25명 배치, 임시 의무실 운영 및 응급이송 체계 구축.\n[자격요건]\n업종: 경비·안전관리업\n업력: 3년 이상', 'DEVOPS', 24500000, 2, 5, 'ACTIVE', NOW(), NOW());
INSERT INTO courses (title, description, category, price, instructor_id, enrollment_count, status, created_at, updated_at) VALUES ('불꽃축제 관람 부스 설치', '[이벤트] 부산 불꽃축제\n[기간] 2026-10-24 ~ 2026-10-25\n[마감] 2026-10-02\n[지역] 부산 수영\n[기관] 부산광역시청\n[과업] 광안리 해변 관람석 및 VIP 부스 설치, 방풍·차수 시공과 야간 유도등 설치 포함.\n[자격요건]\n업종: 전시·부스 설치업\n업력: 5년 이상\n유사 실적: 10건 이상', 'BACKEND', 72000000, 2, 0, 'ACTIVE', NOW(), NOW());
